---
apiVersion: v1
kind: Service
metadata:
  annotations:
    getambassador.io/config: |
      ---
      apiVersion: ambassador/v0
      kind:  Mapping
      name:  httpbin_mapping
      prefix: /httpbin/
      service: httpbin.org:80
      host_rewrite: httpbin.org
{{- if .Values.ambassador.service.annotations }}
{{ toYaml .Values.ambassador.service.annotations | indent 4 }}
{{- end }}
  labels:
    app: {{ template "chart.name" . }}
    chart: {{ .Chart.Name }}-{{ .Chart.Version }}
    component: "{{ .Values.ambassador.name }}"
    heritage: {{ .Release.Service }}
    release: {{ .Release.Name }}
  name: {{ template "ambassador.fullname" . }}    
spec:
{{- if .Values.ambassador.service.clusterIP }}
  clusterIP: {{ .Values.ambassador.service.clusterIP }}
{{- end }}
{{- if .Values.ambassador.service.externalIPs }}
  externalIPs:
{{ toYaml .Values.ambassador.service.externalIPs | indent 4 }}
{{- end }}
{{- if .Values.ambassador.service.loadBalancerIP }}
  loadBalancerIP: {{ .Values.ambassador.service.loadBalancerIP }}
{{- end }}
{{- if .Values.ambassador.service.loadBalancerSourceRanges }}
  loadBalancerSourceRanges:
  {{- range $cidr := .Values.ambassador.service.loadBalancerSourceRanges }}
    - {{ $cidr }}
  {{- end }}
{{- end }}
  ports:
    - name: http
      port: {{ .Values.ambassador.service.servicePort }}
      protocol: TCP
      targetPort: 80
    {{- if .Values.ambassador.service.nodePort }}
      nodePort: {{ .Values.ambassador.service.nodePort }}
    {{- end }}
  selector:
    app: {{ template "chart.name" . }}
    component: {{ .Values.ambassador.name }}
    release: {{ .Release.Name }}
  type: {{ .Values.ambassador.service.type }}
